### ISSUE TITLE
Fix the functionality of the search button on dzcode

### ISSUE THREAD

**Issue by AhmedAbdelhak1** [dzcode-io/dzcode.io#156]
**Describe the bug**
when pushing the search button nothing happen. 

**To Reproduce**
1. Go to 'https://www.dzcode.io/'
2. Click on 'Search button on the left side on the top of the website'

**Expected behavior**
It should be a text area for writing when pushing the search button.

**Desktop (please complete the following information):**
 - OS: [windows 10]
 

**Additional context**
Browser: Google Chrome.

**Comment by ZibanPirate** [comment]
Thanks for reporting the bug @AhmedAbdelhak1 will investigate ASAP

**Comment by AM-77** [comment]
The problem is: there is no event handling nor the input field. the whole search functionality does not exist at all.

https://github.com/dzcode-io/dzcode.io/blob/f56f2fda7c0ad5c0eec370ca8383ac6939a1498b/frontend/src/apps/main/components/navbar/index.tsx#L135

**Comment by ZibanPirate** [comment]
@AM-77 and @AhmedAbdelhak1 , since the content was not clear at the time we implemented the search component, we didn't have a clear decision on what to search for, but now it's clear that we search for the three main sections of the website (documentation, projects, article), will postpone this feature for the next [milestone](https://github.com/dzcode-io/dzcode.io/milestones)

**Comment by NurElHuda** [comment]
This one will be handled in #216
