### ISSUE TITLE
The mobile app does not switch to dark mode in Android when changing the theme from system

### ISSUE THREAD

**Issue by Omar-Belghaouti** [dzcode-io/dzcode.io#367]
**Describe the bug**
I tried the application in an Android device and when I try to change the system theme to dark mode the app does not change it appearance to dark mode. I am not sure if this happens as well for iOS devices.

**To Reproduce**

1. Open dzcode app on Android.
2. Change the system theme to dark mode.
3. The app doesn't change its appearance to dark mode as well.

**Expected behavior**
Change the app appearance immediately when changing the system theme.

**Environment:**

- OS: Android 10.

**Additional context**
I have found that this issue is still opened [here](https://github.com/facebook/react-native/issues/28525) and maybe the solution for this can be found [here](https://github.com/expo/react-native-appearance).

**Comment by ZibanPirate** [comment]
similar issue for iOS too, where when i switch system themes, the app switches two times.

i will try [this suggestion](https://github.com/facebook/react-native/issues/28525#issuecomment-841812810) and see, otherwise i will go with [the debounce suggestion](https://github.com/facebook/react-native/issues/28525#issuecomment-666244448)
